//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haberler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public haber()
        {
            this.yorum = new HashSet<yorum>();
        }
    
        public int haberId { get; set; }
        public string haberBasligi { get; set; }
        public string haberIcerik { get; set; }
        public string haberOlusTarih { get; set; }
        public string haberDuzTarih { get; set; }
        public string haberImgUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorum> yorum { get; set; }
    }
}
