//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haberler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int yorumId { get; set; }
        public string yorumIcerik { get; set; }
        public int yorumLike { get; set; }
        public int yorumKullaniciId { get; set; }
        public Nullable<int> yorumHaberId { get; set; }
        public Nullable<int> yorumMakaleId { get; set; }
        public string yorumOlusTarih { get; set; }
        public string yorumDuzTarih { get; set; }
    
        public virtual haber haber { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual makale makale { get; set; }
    }
}
